name: NobyDa-sync
on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-NobyDa_Script
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: fals
         
      - name: sync NobyDa_Script
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/NobyDa/Script.git"
          source_branch: "master"
          destination_branch: "NobyDa"
          github_token: ${{ secrets.PAT }}
